import Head from 'next/head';
import React from 'react';
import KarnikBar from '../componentsfolders/menuebar/karnikbar';
import NavbarBottom from '../componentsfolders/menuebottom/navbar_bottom';
import Companys from '../componentsfolders/companysliders/companys_slider';
import Footer from '../componentsfolders/footer/footer';
import JobsAdvertisings from '../componentsfolders/adscomponents/jobs_advertising';
export default function Home() {
  return (
    <>
      <Head>
        <title>karnik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <KarnikBar/>
      <NavbarBottom/>
      <Companys/>
      <JobsAdvertisings/>
      <Footer/>
    </>
  )
}
